[package]
name = "aoc-2019-1"
version = "0.1.0"
authors = ["Markku Halinen <markkuh@unity3d.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "main"
path = "src/main.rs"

[dependencies]
